'use client'
import React, { useState, useRef, useEffect } from 'react';
import { Button } from 'flowbite-react';
import EChartsComponent from '@/graphs/EChartsComponent';
import { MetricsService } from '@/services/MetricsService';
import { cumulativeSum } from '@/lib/utils';

const MetricsPage = () => {  
  const [ trendChartData, setTrendChartData ] = useState<any>(null);
  const fetchVixData = async () => {
    const serv = new MetricsService();
    const data: any[] = await serv.getVixData();
    const xValues = data.map(obj => obj.x);
    const yValues = data.map(obj => obj.y);
    const yCumValues = cumulativeSum(yValues);
    const chartData = {
      tooltip: { trigger: 'axis', },
      legend: {
        data: ['적치량', '누적적치량'],
        bottom: 0,
      },
      grid: {
        top: 20,       // 그래프 위쪽 여백
        bottom: 60,    // 범례를 고려해 조금 더 공간 줌
        left: 50,
        right: 50
      },
      xAxis: { type: 'category', data: xValues },
      yAxis: [ 
        { 
          type: 'value',
          position: 'left',
          min: 0,
          max: Math.max(...yValues)
        },
        {
          type: 'value',
          position: 'right',
          min: 0,
          max: Math.max(...yCumValues)
        }
      ],
      series: [
        {
          name: '적치량', type: 'bar',
          data: yValues,
          emphasis: { focus: 'series' },
          yAxisIndex: 0,
          itemStyle: { color: '#0D6EFD' }
        },
        {
          name: '누적적치량', type: 'line',
          data: yCumValues,
          emphasis: { focus: 'series' },
          yAxisIndex: 1,
          itemStyle: { color: '#57C663' }
        }
      ]
    };
    setTrendChartData(chartData);
  };

  useEffect(()=> {
    fetchVixData();
  }, [])

  return (
    <div>
      <div className="flex flex-col md:flex-row">
        <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
        <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col md:flex-row">
      <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
        <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col md:flex-row">
      <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
        <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col md:flex-row">
      <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
        <div className="w-full md:w-1/2 h-[400px] p-3">
          <div className="w-full h-full flex items-center bg-white rounded-lg shadow-lg">
            <div className="w-[70%] h-[90%]">
              <EChartsComponent chartData={trendChartData} width={'100%'} height={'100%'} />
            </div>
            <div className="w-[30%] h-[100%] p-3">
              <div className="w-full h-[40px] flex items-center border-b border-b-[var(--black-night)]">
                <strong>VIX</strong>
              </div>
              <div className="w-full h-[calc(100%-60px)] whitespace-pre-wrap break-words overflow-x-auto mt-2.5">
                VIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIXVIX
              </div>
            </div>
          </div>
        </div>
      </div>      
    </div>
  );
};

export default MetricsPage;